package com.chameleonforensics.chameleon;

import android.content.Context;
import android.os.Build;
import android.util.Log;

import org.json.JSONObject;

import java.io.File;
import java.io.FileWriter;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Append-only event logger. Each call writes one JSON line:
 * {"ts":"...","feature":"AntiAgent","action":"triggered","extra":"...","sdk":34}
 *
 * File location:
 * Android/data/<pkg>/files/reports/session-<yyyymmdd-hhmmss>.ndjson
 */

public final class ReportCore {
    private static final String TAG = "ReportCore";
    private static volatile String sessionId;
    private static final Object LOCK = new Object();

    private ReportCore() {}

    public static void init(Context ctx) {
        ensureSession(ctx);

        try {
            String[] allFeatures = FeatureRegistry.featureClasses;
            if (allFeatures != null) {
                for (String f : FeatureRegistry.featureClasses) {
                    FeatureStatusStore.initFeature(f);
                    recordTriggerState(ctx, f, "initialising");
                }
            }
        } catch (Throwable t) {
            Log.e(TAG, "Failed logging initial untriggered features", t);
        }
    }

    /** Minimal call for features (smali-friendly): */
    public static void recordTrigger(Context ctx, String featureName) {
        recordTriggerState(ctx, featureName, "triggered", null);
    }

    /** Richer variant with extras (JSON string or plain text): */
    public static void recordTrigger(Context ctx, String featureName, String extra) {
        recordTriggerState(ctx, featureName, "triggered", extra);
    }

    /** Used by both trigger and untriggered paths */
    public static void recordTriggerState(Context ctx, String featureName, String action) {
        recordTriggerState(ctx, featureName, action, null);
    }

    public static void recordTriggerState(Context ctx, String featureName, String action, String extra) {
        try {
            ctx = ctx.getApplicationContext();
            ensureSession(ctx);

            JSONObject line = new JSONObject();
            String ts = nowIso();
            line.put("ts", ts);
            line.put("feature", safe(featureName));
            line.put("action", safe(action));
            if (extra != null && !extra.isEmpty()) line.put("extra", extra);
            line.put("sdk", Build.VERSION.SDK_INT);

            File out = getNdjsonFile(ctx);
            synchronized (LOCK) {
                try (FileWriter fw = new FileWriter(out, true)) {
                    fw.write(line.toString());
                    fw.write("\n");
                }
            }

            if ("triggered".equals(action)) {
                UiInjector.markTriggered(featureName, ts);
                FeatureStatusStore.markTriggered(featureName, ts);
                ChameleonForegroundService.refreshNotification(ctx);
                ChameleonForegroundService.showFeatureTriggeredNotification(ctx, featureName, ts);
            }

        } catch (Throwable t) {
            Log.e(TAG, "recordTriggerState failed", t);
        }
    }

    /** Returns the append-only NDJSON file for this run. */
    public static File getNdjsonFile(Context ctx) {
        File dir = new File(ctx.getExternalFilesDir(null), "reports");
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, "session-" + ensureSession(ctx) + ".ndjson");
    }

    /** Finalized summary JSON path (generated by ReportFinalizer). */
    public static File getFinalJsonFile(Context ctx) {
        File dir = new File(ctx.getExternalFilesDir(null), "reports");
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, "session-" + ensureSession(ctx) + ".json");
    }

    private static String ensureSession(Context ctx) {
        if (sessionId == null) {
            synchronized (ReportCore.class) {
                if (sessionId == null) {
                    sessionId = new SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(new Date());
                }
            }
        }
        return sessionId;
    }

    private static String nowIso() {
        return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.US).format(new Date());
    }

    private static String safe(String s) {
        return s == null ? "unknown" : s;
    }
}